import argparse
import sys
from params import defaults

DESC='''Based on the GCode generated by the first script, calculate the new e-step.

Based on https://mattshub.com/blogs/blog/extruder-calibration.'''

parser = argparse.ArgumentParser(description=DESC, formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('--extrusion_distance', type=int, default=defaults.EXTRUDE_MM, help='Distance to extrude.')
parser.add_argument('--mark_distance', type=int, default=defaults.MARK_MM, help='Distance to mark the filament at.')
parser.add_argument('--leftover_distance', type=float, required=True, help='Distance to mark the filament at.')
parser.add_argument('--prev_estep', type=float, required=True, help='Previous E-step value used (Query using M503 on Marlin).')

args = parser.parse_args()

correction_mult = float(args.extrusion_distance) / (args.mark_distance - args.leftover_distance)
new_estep = correction_mult * args.prev_estep
print('M92 E{:.1f} ; Apply new e-step'.format(new_estep))
print('M500 ; Persist settings')
